package org.example.sortingalgorithmsvisualization.Controller.Adaptor;

import org.example.sortingalgorithmsvisualization.Controller.ArrayFileReader;
import org.example.sortingalgorithmsvisualization.Controller.ArrayGenerator;
import org.example.sortingalgorithmsvisualization.Controller.ArrayType;
import org.example.sortingalgorithmsvisualization.Controller.ComparisonArray;

import java.io.IOException;
import java.util.ArrayList;

public class ArrayAdaptor implements ComparisonArrayAdaptor {
    private ArrayGenerator generator;
    private ArrayFileReader reader;

    public ArrayAdaptor() {
        this.generator = new ArrayGenerator();
        this.reader = new ArrayFileReader();
    }


    @Override
    public ArrayList<ComparisonArray> getAutoGeneratedArrays(ArrayList<Integer> sizes, ArrayType[] modes, int max) {
        ArrayList<ComparisonArray> arrays = new ArrayList<>();
        for (int size : sizes) {
            for (ArrayType mode : modes) {
                int[] array = switch (mode) {
                    case RANDOM -> generator.randomArray(size, max);
                    case SORTED -> generator.sortedArray(size, max);
                    case INVERSELY_SORTED -> generator.inverselySortedArray(size, max);
                    case NEARLY_SORTED -> generator.nearlySortedArray(size, max);
                    default -> throw new IllegalArgumentException("Unsupported Array type");
                };
                arrays.add(new ComparisonArray(array, mode.toString()));
            }
        }
        return arrays;
    }

    @Override
    public ArrayList<ComparisonArray> getFileArrays(String[] paths) {
        ArrayList<ComparisonArray> arrays = new ArrayList<>();
        for (String path : paths) {
            try {
                int[] arr = reader.readArray(path);
                arrays.add(new ComparisonArray(arr, path));
            } catch (IOException e) {
                throw new IllegalArgumentException("Failed to read file: " + path, e);
            }
        }
        return arrays;
    }
}
