package org.example.sortingalgorithmsvisualization.Controller.Adaptor;

import org.example.sortingalgorithmsvisualization.Controller.ArrayType;
import org.example.sortingalgorithmsvisualization.Controller.ComparisonArray;

import java.util.ArrayList;

public interface ComparisonArrayAdaptor {
    ArrayList<ComparisonArray> getAutoGeneratedArrays(ArrayList<Integer> sizes , ArrayType[] modes , int max);
    ArrayList<ComparisonArray> getFileArrays(String[] paths) ;
}
