package org.example.sortingalgorithmsvisualization.Model;

import org.example.sortingalgorithmsvisualization.Controller.Adaptor.ArrayAdaptor;
import org.example.sortingalgorithmsvisualization.Controller.Adaptor.ComparisonArrayAdaptor;
import org.example.sortingalgorithmsvisualization.Controller.ArrayFileReader;
import org.example.sortingalgorithmsvisualization.Controller.ArrayGenerator;
import org.example.sortingalgorithmsvisualization.Controller.ComparisonArray;
import org.example.sortingalgorithmsvisualization.Controller.InputData;
import org.example.sortingalgorithmsvisualization.Model.Observers.OperationsCounter;
import org.example.sortingalgorithmsvisualization.Model.PureSorting.SortingStrategy;
import org.example.sortingalgorithmsvisualization.Model.SimulationSorting.Observer.AbstractSimulationSorting;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;

public class ComparisonManager {
    private InputData data;
    private final SortingAlgorithmsFactory factory = new SortingAlgorithmsFactory();
    private LinkedHashMap<ComparisonArray , List<ComparisonStat>> statTable = new LinkedHashMap<>() ;
    private final ComparisonArrayAdaptor adaptor = new ArrayAdaptor() ;
    public InputData getData() {
        return data;
    }

    public void setData(InputData data) {
        this.data = data;
    }

    public LinkedHashMap<ComparisonArray , List<ComparisonStat>> runComparison() {
        ArrayList<ComparisonArray> arrays = getArrays() ;
        for (ComparisonArray arr : arrays) {
            ArrayList<ComparisonStat> statList = new ArrayList<>() ;
            for (String algo : data.algorithms) {
                // Don't forget to add the num of runs to input data
                ComparisonStat stat = runSingleRun(arr.array(), algo, arr.generationMode(), 10) ;
                statList.add(stat) ;
            }
            statTable.put(arr, statList) ;
        }
        return statTable ;
    }

    private ArrayList<ComparisonArray> getArrays() {
        if (data.autoGeneration) {
            return adaptor.getAutoGeneratedArrays(data.arraySizes, data.generationMods, data.maxValue);
        } else {
            return adaptor.getFileArrays((String[]) data.files.stream().map(f -> f.getPath()).toArray());
        }
    }

    private ComparisonStat runSingleRun(int[] array, String algorithm, String generationMode, int numOfRuns) {
        AbstractSimulationSorting simulationSorting = factory.createSimulationAlgorithm(algorithm);
        SortingStrategy sort = factory.createPureAlgorithm(algorithm);
        ComparisonStat stat = new ComparisonStat();
        OperationsCounter counter = new OperationsCounter();
        simulationSorting.register(counter);
        int[] cloneArray = array.clone();
        simulationSorting.sort(cloneArray);
        stat.numOfComparison = counter.getComparison();
        stat.numOfInterchange = counter.getSwap();
        // loop over the array to get the average tun time
        double minTime = Double.POSITIVE_INFINITY;
        double maxTime = Double.NEGATIVE_INFINITY;
        double totalTime = 0;
        for (int i = 0; i < numOfRuns; i++) {
            // The reason for native arraycopy is to avoid GC overhead
            // Such that the time is as accurate as possible
            System.arraycopy(array, 0, cloneArray, 0, array.length);
            long start = System.nanoTime();
            sort.sort(cloneArray);
            long end = System.nanoTime();
            long time = end - start;
            minTime = time < minTime ? time : minTime;
            maxTime = time > maxTime ? time : maxTime;
            totalTime += time;
        }
        stat.minTime = minTime;
        stat.maxTime = maxTime;
        stat.averageTime = totalTime / 10;
        stat.generationMode = generationMode;
        stat.arraySize = array.length;
        stat.numberOfruns = numOfRuns;
        stat.sortingAlgorithm = algorithm;
        return stat;
    }

}
