package org.example.sortingalgorithmsvisualization.View;

import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.SceneAntialiasing;
import javafx.scene.control.*;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Paint;
import javafx.stage.FileChooser;

import java.io.File;
import java.util.List;

public class InputScene extends Scene {
    public InputScene(Parent parent) {
        super(parent);
    }

    public InputScene(Parent parent, double v, double v1) {
        super(parent, v, v1);
    }

    public InputScene(Parent parent, Paint paint) {
        super(parent, paint);
    }

    public InputScene(Parent parent, double v, double v1, boolean b, SceneAntialiasing sceneAntialiasing) {
        super(parent, v, v1, b, sceneAntialiasing);
    }

    public InputScene(Parent parent, double v, double v1, boolean b) {
        super(parent, v, v1, b);
    }

    public InputScene(Parent parent, double v, double v1, Paint paint) {
        super(parent, v, v1, paint);
    }

    String mode ;

    // Array generation / File loading
    RadioButton autoGenerated = new RadioButton("Auto Generated Array") ;
    RadioButton fileLoaded = new RadioButton("Load arrays from file");

    // Group the previous two options into toggle group
    ToggleGroup arrayGenerationGroup = new ToggleGroup() ;

    // Auto Generation options
    TextField arraySize = new TextField() ;
    TextField arrayMaxValue = new TextField() ;

    // Generation type check boxes

    CheckBox randomArray = new CheckBox("Random Array") ;
    CheckBox sortedArray = new CheckBox("Sorted Array") ;
    CheckBox inverselySorted = new CheckBox("Reversed Array") ;
    CheckBox nearlySortedArray = new CheckBox("Nearly Sorted Array") ;

    FileChooser fileChooser = new FileChooser();

    VBox arrayGenerationLayout ;
    Button chooseFileButton = new Button("Choose Files") ;

    List<File> files ;

    HBox fileButtonLayout ;

    private final CheckBox chkMergeSort     = new CheckBox("Merge Sort");
    private final CheckBox chkQuickSort     = new CheckBox("Quick Sort");
    private final CheckBox chkHeapSort      = new CheckBox("Heap Sort");
    private final CheckBox chkBubbleSort    = new CheckBox("Bubble Sort");
    private final CheckBox chkInsertionSort = new CheckBox("Insertion Sort");
    private final CheckBox chkSelectionSort = new CheckBox("Selection Sort");

    HBox sortBoxes = new HBox(10) ;

    Button startButton = new Button("Start") ;
    Button resetButton = new Button("Reset") ;



    public void initializeScene() {
        Label title = new Label("Sorting Algorithms");
        Label subTitle = new Label(mode) ;

        Label arrayConfig = new Label("📦  Array Configuration"); ;
        autoGenerated.setToggleGroup(arrayGenerationGroup);
        fileLoaded.setToggleGroup(arrayGenerationGroup);

        // set Auto Generation to be the default mode
        autoGenerated.setSelected(true);

        HBox arrayGenerationBox = new HBox(10 , autoGenerated , fileLoaded) ;

        VBox arrayInputPara = new VBox(10,arraySize,arrayMaxValue) ;
        arraySize.setPromptText("Enter array size");
        arrayMaxValue.setPromptText("Enter max value");
        HBox arrayType1 = new HBox(10,randomArray,inverselySorted) ;
        HBox arrayType2 = new HBox(10,sortedArray,nearlySortedArray) ;
        VBox arrayTypes = new VBox(10,arrayType1,arrayType2) ;
        arrayGenerationLayout = new VBox(10,arrayInputPara,arrayTypes) ;
        arrayGenerationLayout.setVisible(true);
        // bind the array generation fields to radio button
        arrayGenerationLayout.visibleProperty().bind(autoGenerated.selectedProperty());

        fileChooser.setTitle("Choose file or multiple files");
        // restrict the options to only text files
        fileChooser.getExtensionFilters().add(
                new FileChooser.ExtensionFilter("Text Files", "*.txt")
        );
        fileButtonLayout = new HBox(10,chooseFileButton) ;
        fileButtonLayout.visibleProperty().bind(fileLoaded.selectedProperty());

        VBox algorithmsList1 = new VBox(10 , chkBubbleSort,chkInsertionSort,chkSelectionSort) ;
        VBox algorithmsList2 = new VBox(10 , chkHeapSort,chkMergeSort,chkQuickSort) ;
        sortBoxes.getChildren().addAll(algorithmsList1,algorithmsList2) ;

    }

    private void listenersWiring() {
        arraySize.textProperty().addListener((obs, oldVal, newVal) -> {
            if (!newVal.matches("[0-9,]*")) {
                arraySize.setText(newVal.replaceAll("[^0-9,]", ""));
            }
        });

        arrayMaxValue.textProperty().addListener((obs, oldVal, newVal) -> {
            if (!newVal.matches("[0-9,]*")) {
                arrayMaxValue.setText(newVal.replaceAll("[^0-9,]", ""));
            }
        });

        // Listener to toggle between array generation and file reading
//        arrayGenerationGroup.selectedToggleProperty().addListener((obs,oldVal,newVal)->{
//            boolean autoSelected = autoGenerated.isSelected() ;
//            arrayGenerationLayout.setVisible(autoSelected);
//            arrayGenerationLayout.setManaged(autoSelected);
//        });

        chooseFileButton.setOnAction(event -> {
            files = fileChooser.showOpenMultipleDialog(this.getWindow()) ;
        });

        startButton.setOnAction(event -> {
            // TODO Go to visualization or comparison views
        });

        resetButton.setOnAction(event -> {
            //TODO Reset All Fields
        });



    }
}
