package org.example.sortingalgorithmsvisualization.View;

import javafx.animation.*;
import javafx.beans.binding.BooleanBinding;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.SceneAntialiasing;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.paint.Paint;
import javafx.scene.shape.Rectangle;
import javafx.stage.FileChooser;
import javafx.stage.Screen;
import javafx.util.Duration;
import org.example.sortingalgorithmsvisualization.Controller.ArrayType;
import org.example.sortingalgorithmsvisualization.Controller.Controller;
import org.example.sortingalgorithmsvisualization.Controller.InputData;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class InputScene extends StackPane implements Animatable {
    String mode;

    //This will be passed at the beginning when caching different scene
    Controller controller ;

    // Array generation / File loading
    RadioButton autoGenerated = new RadioButton("Auto Generated Array");
    RadioButton fileLoaded = new RadioButton("Load arrays from file");

    // Group the previous two options into toggle group
    ToggleGroup arrayGenerationGroup = new ToggleGroup();

    // Auto Generation options
    TextField arraySize = new TextField();
    TextField arrayMaxValue = new TextField();

    // Generation type check boxes

    CheckBox randomArray = new CheckBox("Random Array");
    CheckBox sortedArray = new CheckBox("Sorted Array");
    CheckBox inverselySorted = new CheckBox("Reversed Array");
    CheckBox nearlySortedArray = new CheckBox("Nearly Sorted Array");

    FileChooser fileChooser = new FileChooser();

    VBox arrayGenerationLayout;
    Button chooseFileButton = new Button("Choose Files");

    List<File> files;

    HBox fileButtonLayout;

    Label lblAlgorithms = new Label("🧠  Algorithm Selection");
    final CheckBox chkMergeSort = new CheckBox("Merge Sort");
    final CheckBox chkQuickSort = new CheckBox("Quick Sort");
    final CheckBox chkHeapSort = new CheckBox("Heap Sort");
    final CheckBox chkBubbleSort = new CheckBox("Bubble Sort");
    final CheckBox chkInsertionSort = new CheckBox("Insertion Sort");
    final CheckBox chkSelectionSort = new CheckBox("Selection Sort");

    // A list for easily iterating over boxes
    List<CheckBox> checkBoxes = List.of(chkMergeSort, chkQuickSort, chkHeapSort, chkBubbleSort, chkInsertionSort, chkSelectionSort);

    HBox sortBoxes = new HBox(24);

    Button startButton = new Button("Start");
    Button resetButton = new Button("Reset");
    // For comparison mode to use auto config
    Button autoButton = new Button("Auto") ;
    HBox btnRow;

    VBox mainRoot = new VBox();

    Label title;
    Label subTitle;
    Label arrayConfig;


    // an array to hold timelines
    ArrayList<Timeline> animations = new ArrayList<>();

    public InputScene(String mode) {
        super(new StackPane());
        this.mode = mode;
        initializeScene();
    }


    public void initializeScene() {
        Pane backgroundAnimation = animatedBars(Screen.getPrimary().getVisualBounds().getWidth(), Screen.getPrimary().getVisualBounds().getHeight());
        this.getChildren().addAll(backgroundAnimation, mainRoot);

        title = new Label("Sorting Algorithms");
        subTitle = new Label(mode);
        arrayConfig = new Label("📦  Array Configuration");

        autoGenerated.setToggleGroup(arrayGenerationGroup);
        fileLoaded.setToggleGroup(arrayGenerationGroup);

        // set Auto Generation to be the default mode
        autoGenerated.setSelected(true);

        HBox arrayGenerationBox = new HBox(16, autoGenerated, fileLoaded);
        arrayGenerationBox.setAlignment(Pos.CENTER_LEFT);

        VBox arrayInputPara = new VBox(10, arraySize, arrayMaxValue);
        arraySize.setPromptText("Enter array size");
        arrayMaxValue.setPromptText("Enter max value");
        arrayInputPara.setAlignment(Pos.CENTER_LEFT);
        HBox.setHgrow(arraySize, Priority.ALWAYS);
        HBox.setHgrow(arrayMaxValue, Priority.ALWAYS);
        HBox arrayType1 = new HBox(10, randomArray, inverselySorted);
        HBox arrayType2 = new HBox(10, sortedArray, nearlySortedArray);
        VBox arrayTypes = new VBox(10, arrayType1, arrayType2);
        arrayGenerationLayout = new VBox(10, arrayInputPara, arrayTypes);
        arrayGenerationLayout.setVisible(true);
        arrayGenerationLayout.setPadding(new Insets(0, 0, 0, 16));
        // bind the array generation fields to radio button
        arrayGenerationLayout.visibleProperty().bind(autoGenerated.selectedProperty());
        arrayGenerationLayout.managedProperty().bind(autoGenerated.selectedProperty());

        fileChooser.setTitle("Choose file or multiple files");
        // restrict the options to only text files
        fileChooser.getExtensionFilters().add(
                new FileChooser.ExtensionFilter("Text Files", "*.txt")
        );
        fileButtonLayout = new HBox(10, chooseFileButton);
        fileButtonLayout.visibleProperty().bind(fileLoaded.selectedProperty());
        fileButtonLayout.managedProperty().bind(fileLoaded.selectedProperty());
        fileButtonLayout.setAlignment(Pos.CENTER_LEFT);
        fileButtonLayout.setPadding(new Insets(0, 0, 0, 16));


        VBox algorithmsList1 = new VBox(10, chkBubbleSort, chkInsertionSort, chkSelectionSort);
        VBox algorithmsList2 = new VBox(10, chkHeapSort, chkMergeSort, chkQuickSort);
        sortBoxes.getChildren().addAll(algorithmsList1, algorithmsList2);

        startButton.setMaxWidth(Double.MAX_VALUE);
        resetButton.setMaxWidth(Double.MAX_VALUE);
        autoButton.setMaxWidth(Double.MAX_VALUE);
        autoButton.setVisible(mode.equalsIgnoreCase("Comparison Mode"));
        autoButton.setManaged(mode.equalsIgnoreCase("Comparison Mode"));
        btnRow = new HBox(12, startButton, resetButton , autoButton);
        btnRow.setAlignment(Pos.CENTER);
        HBox.setHgrow(startButton, Priority.ALWAYS);
        HBox.setHgrow(resetButton, Priority.ALWAYS);
        HBox.setHgrow(autoButton, Priority.ALWAYS);

        // The main root for the scene add all nodes to it
        mainRoot.getChildren().setAll(title, subTitle, arrayConfig, arrayGenerationBox, arrayGenerationLayout, lblAlgorithms, fileButtonLayout, sortBoxes, startButton, resetButton,autoButton);

        // Wire up event listeners
        listenersWiring();

        // Apply styles
        applyStyles();
    }

    public void listenersWiring() {
        arraySize.textProperty().addListener((obs, oldVal, newVal) -> {
            if (!newVal.matches("[0-9,]*")) {
                arraySize.setText(newVal.replaceAll("[^0-9,]", ""));
            }
        });

        arrayMaxValue.textProperty().addListener((obs, oldVal, newVal) -> {
            if (!newVal.matches("[0-9,]*")) {
                arrayMaxValue.setText(newVal.replaceAll("[^0-9,]", ""));
            }
        });

        BooleanBinding autoGenerationInvalid = arraySize.textProperty().isEmpty().
                or(randomArray.selectedProperty().
                        or(sortedArray.selectedProperty().
                                or(inverselySorted.selectedProperty().
                                        or(nearlySortedArray.selectedProperty()))).not());

        BooleanBinding fileInvalid = new BooleanBinding() {
            {
                super.bind(chooseFileButton.focusedProperty());
            }
            @Override
            protected boolean computeValue() {
                return fileLoaded.isSelected() && (files == null || files.isEmpty());
            }
        } ;
        chooseFileButton.setOnAction(event -> {
            files = fileChooser.showOpenMultipleDialog(this.getScene().getWindow());
        });

        startButton.disableProperty().bind(
                autoGenerated.selectedProperty().and(autoGenerationInvalid)
                .or(fileLoaded.selectedProperty().and(fileInvalid))) ;

        autoButton.setOnAction( e-> {
            controller.runAutoComparison();
        });

        startButton.setOnAction(event -> {
            // Collect data
            InputData data = collectData() ;
            // send data to controller
            controller.setData(data);
            // set the mode
            controller.setMode(mode);
            // now the controller will process the data
            controller.processData();
        });

        resetButton.setOnAction(event -> {
            //TODO Reset All Fields
        });


    }

    public void applyStyles() {
        getStylesheets().add(
                getClass().getResource("/main-scene.css").toExternalForm()
        );
        this.setStyle("-fx-background-color: #1a1a2e;");

        mainRoot.setSpacing(18);
        mainRoot.setPadding(new Insets(28, 32, 28, 32));
        mainRoot.setMaxWidth(420);
        mainRoot.setMaxHeight(800);
        mainRoot.setAlignment(Pos.TOP_CENTER);

        mainRoot.getStyleClass().add("input-form-pane");

        // Section labels
        arrayConfig.getStyleClass().add("section-label");
        lblAlgorithms.getStyleClass().add("section-label");

        // Buttons
        startButton.getStyleClass().add("btn-start");
        resetButton.getStyleClass().add("btn-reset");

        title.getStyleClass().add("form-title");
        subTitle.getStyleClass().add("form-subtitle");
    }

    // for visualization mode until implementing asymptotic functions plotting
    private final Color BAR_COLOR = Color.web("#38bdf8");  // soft cyan

    private Pane animatedBars(double width, double height) {
        Pane pane = new Pane();
        int numBars = 50;
        double gap = 4;
        double barW = width / numBars - gap;
        Random rng = new Random();
        for (int i = 0; i < numBars; i++) {
            Rectangle bar = new Rectangle();
            double x = (barW + gap) * i + gap / 2;
            bar.setX(x);
            bar.setWidth(barW);

            double startHeight = 50 + rng.nextDouble() * 80;
            double maxHeight = rng.nextDouble() * height;

            bar.setHeight(startHeight);
            bar.setY(height - startHeight);

            bar.setArcWidth(12);
            bar.setArcHeight(12);

            bar.setFill(BAR_COLOR);

            // Animation for bars
            Timeline tl = new Timeline();
            double dur = 1.5 + rng.nextDouble() * 2.5;
            KeyValue kvh1 = new KeyValue(bar.heightProperty(), startHeight, Interpolator.EASE_BOTH);
            KeyValue kvh2 = new KeyValue(bar.heightProperty(), maxHeight, Interpolator.EASE_BOTH);
            KeyValue kvy1 = new KeyValue(bar.yProperty(), height - startHeight, Interpolator.EASE_BOTH);
            KeyValue kvy2 = new KeyValue(bar.yProperty(), height - maxHeight, Interpolator.EASE_BOTH);

            KeyFrame frame1 = new KeyFrame(Duration.ZERO, kvh1, kvy1);
            KeyFrame frame2 = new KeyFrame(Duration.seconds(dur), kvh2, kvy2);
            tl.getKeyFrames().addAll(frame1, frame2);

            tl.setAutoReverse(true);
            tl.setCycleCount(Animation.INDEFINITE);
            tl.setDelay(Duration.seconds(3 * rng.nextDouble()));
            tl.play();
            animations.add(tl);
            pane.getChildren().add(bar);

        }
        return pane;
    }

    @Override
    public void play() {
        animations.forEach(Timeline::play);
    }

    @Override
    public void pause() {
        animations.forEach(Timeline::pause);
    }

    @Override
    public void stop() {
        animations.forEach(Timeline::stop);
    }

    public InputData collectData() {
        InputData data = new InputData();
        if (autoGenerated.isSelected()) {
            data.autoGeneration = true;
            String[] parts = arraySize.getText().split(",");
            for (String part : parts) {
                data.arraySizes.add(Integer.valueOf(part));
            }
            data.maxValue = Integer.parseInt(arrayMaxValue.getText());
            ArrayList<ArrayType> generationMode = new ArrayList<>() ;
            if(randomArray.isSelected()) generationMode.add(ArrayType.RANDOM) ;
            if (sortedArray.isSelected()) generationMode.add(ArrayType.SORTED) ;
            if(inverselySorted.isSelected()) generationMode.add(ArrayType.INVERSELY_SORTED) ;
            if (nearlySortedArray.isSelected()) generationMode.add(ArrayType.NEARLY_SORTED) ;
            data.generationMods = generationMode.toArray(new ArrayType[0]);
        } else {
            data.autoGeneration = false;
            data.files = (ArrayList<File>) this.files;
        }
        for (CheckBox box : checkBoxes) {
            if (box.isSelected()) data.algorithms.add(box.getText());
        }
        return data;
    }

    public String getMode() {
        return mode;
    }

    public void setMode(String mode) {
        this.mode = mode;
        subTitle.setText(mode);
        autoButton.setVisible(mode.equalsIgnoreCase("Comparison Mode"));
        autoButton.setManaged(mode.equalsIgnoreCase("Comparison Mode"));
    }
}
